# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='site',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='blogcategorys', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='sites.Site'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
