# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogcategorys', to='blog.Blog', verbose_name='Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='blog.Blog', verbose_name='Blog'),
            preserve_default=False,
        ),
    ]
