# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 16:00
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160107_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image'),
        ),
    ]
