# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bct_galleries', '0002_auto_20160111_1923'),
        ('blog', '0007_blog_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='bct_galleries.Gallery', verbose_name='Gallery'),
            preserve_default=False,
        ),
    ]
