# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='map_url',
            field=models.CharField(blank=True, help_text='Google Maps URL', max_length=2000, null=True, verbose_name='Map URL'),
        ),
    ]
