# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20160112_1646'),
        ('blog', '0009_blogpost_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='portal.Country', verbose_name='Country'),
            preserve_default=False,
        ),
    ]
