# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 18:19
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.blog.models
import mezzanine.core.fields
import topnotchdev.files_widget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=topnotchdev.files_widget.fields.ImagesField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to=mezzanine.blog.models.blog_upload_to, verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, upload_to=mezzanine.blog.models.post_upload_to, verbose_name='Featured Image'),
        ),
    ]
