# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160113_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='site',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='site',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='country',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='related_posts',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='site',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
