# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site'),
        ),
    ]
