# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20160107_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='value_en',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_pl',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
